### ISSUE TITLE
can i use android_vendor_xiaomi_libra branch lineage-16.0 for compile lineage17

### ISSUE THREAD

**Issue by lx19990999** [WJXXBSH/android_vendor_xiaomi_libra#1]
hello, I'm a newer. I see your xda link https://forum.xda-developers.com/mi-4c/development/rom-lineageos-15-1-16-0-17-0-mi-4c-mi-4s-t4008625.
I want study how to compile lineage.
can i use branch lineage-16.0 for compile lineage17?
thank you

**Comment by WJXXBSH** [comment]
> hello, I'm a newer. I see your xda link https://forum.xda-developers.com/mi-4c/development/rom-lineageos-15-1-16-0-17-0-mi-4c-mi-4s-t4008625.
> I want study how to compile lineage.
> can i use branch lineage-16.0 for compile lineage17?
> thank you

Yes, you can.
If there is a repository with only one branch (like "master" or "lineage-16.0"), it means you could use it across different Android version.
